version: "3.9"

services:
  app:
    image: golang:latest
    working_dir: /app
    volumes:
      - .:/app
    command: go run cmd/main.go
    ports:
      - "8080:8080"
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"


