version: "3.9"

services:
  app:
    image: golang:latest
    working_dir: /app
    env_file:
      - .env
    volumes:
      - .:/app
    command: go run cmd/main.go
    ports:
      - "${PORT}:${PORT}"
    networks:
      - monitoring

  redis:
    image: redis:latest
    env_file:
      - .env
    networks:
      - monitoring
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    depends_on:
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - monitoring
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring    

volumes:
  grafana_data:
  prometheus_data:

networks:
  monitoring:
