basePath: /
definitions:
  handlers.Response:
    properties:
      message:
        type: string
    type: object
host: localhost:5080
info:
  contact: {}
  description: The service is designed to detect and prevent brute-force attacks on
    web resources.
  title: Anti Brute Force Service
  version: "1.0"
paths:
  /api/admins/lists/:
    post:
      consumes:
      - application/json
      description: adds an ip address to the white/black lists for quick access or
        a ban on brute force
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.Response'
      summary: add ip in black/white lists
      tags:
      - adminLists
swagger: "2.0"
